import { emotionTestQuestions, safetyTestQuestions, womenIssueTestQuestions } from "./questions";

export const allAssesments = {
    safety: [{
        id: 1,
        category: 'safety',
        title: 'Safety Test 1',
        description: 'Test your safety knowledge',
        image: '',
        numberOfQuestions: 10,
        onlyWomen: false,
        description: 'Test your safety knowledge',
        allQuestions: safetyTestQuestions,
    },
    {
        id: 2,
        category: 'safety',
        title: 'Safety Test 2',
        description: 'Test your safety knowledge',
        image: '',
        numberOfQuestions: 10,
        onlyWomen: false,
        description: 'Test your safety knowledge',
        allQuestions: safetyTestQuestions,
    }],
    "emotion-quotient": [{
        id: 3,
        category: 'emotion',
        title: 'Emotion Test 1',
        description: 'Test your emotion knowledge',
        image: '',
        numberOfQuestions: 10,
        onlyWomen: false,
        description: 'Test your emotion knowledge',
        allQuestions: emotionTestQuestions,
    },{
        id: 4,
        category: 'emotion',
        title: 'Emotion Test 2',
        description: 'Test your emotion knowledge',
        image: '',
        numberOfQuestions: 10,
        onlyWomen: false,
        description: 'Test your emotion knowledge',
        allQuestions: emotionTestQuestions,
    },
    {
        id: 5,
        category: 'emotion',
        title: 'Emotion Test 3',
        description: 'Test your emotion knowledge',
        image: '',
        numberOfQuestions: 10,
        onlyWomen: false,
        description: 'Test your emotion knowledge',
        allQuestions: emotionTestQuestions ,
    },
],
    "women-issue": [{
        id: 6,
        category: 'women',
        title: 'Women Issue Test 1',
        description: 'Test your women issue knowledge',
        image: '',
        numberOfQuestions: 10,
        onlyWomen: true,
        description: 'Test your women issue knowledge',
        allQuestions: womenIssueTestQuestions,
    },{
        id: 7,
        category: 'women',
        title: 'Women Issue Test 2',
        description: 'Test your women issue knowledge',
        image: '',
        numberOfQuestions: 10,
        onlyWomen: true,
        description: 'Test your women issue knowledge',
        allQuestions: womenIssueTestQuestions,
    }],
    "social-awareness": [{
        id: 8,
        category: 'social',
        title: 'Social Awareness Test 1',
        description: 'Test your social awareness knowledge',
        image: '',
        numberOfQuestions: 10,
        onlyWomen: false,
        description: 'Test your social awareness knowledge',
        allQuestions: [],
    }],
    "fitness-health": [{
        id: 9,
        category: 'fitness',
        title: 'Fitness Health Test 1',
        description: 'Test your fitness health knowledge',
        image: '',
        numberOfQuestions: 10,
        onlyWomen: false,
        description: 'Test your fitness health knowledge',
        allQuestions: [],
    },{
        id: 10,
        category: 'fitness',
        title: 'Fitness Health Test 2',
        description: 'Test your fitness health knowledge',
        image: '',
        numberOfQuestions: 10,
        onlyWomen: false,
        description: 'Test your fitness health knowledge',
        allQuestions: [],
    }],
}